// TODO: Have something to import TextureAtlas as an asset.
// This was generated by a simple parser built in 10 minutes,
// but it's far from being convenient.

use amethyst::assets::{AssetStorage, Loader};
use amethyst::ecs::World;
use amethyst::renderer::{
    MaterialTextureSet, PngFormat, Sprite, SpriteSheet, SpriteSheetHandle, SpriteSheetSet, Texture,
    TextureCoordinates, TextureMetadata, FilterMethod, SamplerInfo, WrapMode
};

const TEXTURE_ID: u64 = 0;
const SPRITESHEET_SIZE: (f32, f32) = (1024.0, 2048.0);

struct SpriteDescription {
    top: f32,
    bottom: f32,
    left: f32,
    right: f32,
}

pub fn load_sprite_sheet(world: &mut World) -> SpriteSheetHandle {
    let texture_handle = {
        let loader = world.read_resource::<Loader>();
        let texture_storage = world.read_resource::<AssetStorage<Texture>>();
        loader.load(
            "texture/isometric_tiles.png",
            PngFormat,
            TextureMetadata::default()
                .with_sampler(SamplerInfo::new(FilterMethod::Trilinear, WrapMode::Border)),
            (),
            &texture_storage,
        )
    };

    let mut material_texture_set = world.write_resource::<MaterialTextureSet>();
    material_texture_set.insert(TEXTURE_ID, texture_handle);

    let mut sprites = Vec::new();
    for i in 0..128 {
        let dims = get_sprite(i);
        let tex_coords = TextureCoordinates {
            left: (dims.left) / SPRITESHEET_SIZE.0,
            right: (dims.right) / SPRITESHEET_SIZE.0,
            bottom: 1.0 - (dims.bottom) / SPRITESHEET_SIZE.1,
            top: 1.0 - (dims.top) / SPRITESHEET_SIZE.1,
        };
        sprites.push(Sprite {
            width: dims.right - dims.left,
            height: dims.bottom - dims.top,
            offsets: [0.0, 0.0],
            tex_coords,
        });
    }

    let sprite_sheet = SpriteSheet {
        texture_id: TEXTURE_ID,
        sprites: sprites,
    };

    let sprite_sheet_handle = {
        let loader = world.read_resource::<Loader>();
        let sprite_sheet_store = world.read_resource::<AssetStorage<SpriteSheet>>();
        loader.load_from_data(sprite_sheet, (), &sprite_sheet_store)
    };

    sprite_sheet_handle
}

fn get_sprite(tile_type: u8) -> SpriteDescription {
    match tile_type {
        000 => SpriteDescription {
            top: 1057.0,
            bottom: 1140.0,
            left: 265.0,
            right: 397.0,
        },
        001 => SpriteDescription {
            top: 1452.0,
            bottom: 1551.0,
            left: 265.0,
            right: 397.0,
        },
        002 => SpriteDescription {
            top: 1369.0,
            bottom: 1452.0,
            left: 265.0,
            right: 397.0,
        },
        003 => SpriteDescription {
            top: 1682.0,
            bottom: 1765.0,
            left: 265.0,
            right: 397.0,
        },
        004 => SpriteDescription {
            top: 1191.0,
            bottom: 1290.0,
            left: 529.0,
            right: 661.0,
        },
        005 => SpriteDescription {
            top: 1551.0,
            bottom: 1682.0,
            left: 265.0,
            right: 397.0,
        },
        006 => SpriteDescription {
            top: 1947.0,
            bottom: 2046.0,
            left: 265.0,
            right: 397.0,
        },
        007 => SpriteDescription {
            top: 1864.0,
            bottom: 1947.0,
            left: 265.0,
            right: 397.0,
        },
        008 => SpriteDescription {
            top: 921.0,
            bottom: 1052.0,
            left: 266.0,
            right: 398.0,
        },
        009 => SpriteDescription {
            top: 281.0,
            bottom: 380.0,
            left: 0.0,
            right: 133.0,
        },
        010 => SpriteDescription {
            top: 1183.0,
            bottom: 1266.0,
            left: 397.0,
            right: 529.0,
        },
        011 => SpriteDescription {
            top: 693.0,
            bottom: 792.0,
            left: 662.0,
            right: 794.0,
        },
        012 => SpriteDescription {
            top: 1052.0,
            bottom: 1183.0,
            left: 397.0,
            right: 529.0,
        },
        013 => SpriteDescription {
            top: 1303.0,
            bottom: 1402.0,
            left: 793.0,
            right: 925.0,
        },
        014 => SpriteDescription {
            top: 380.0,
            bottom: 463.0,
            left: 133.0,
            right: 266.0,
        },
        015 => SpriteDescription {
            top: 1204.0,
            bottom: 1303.0,
            left: 793.0,
            right: 925.0,
        },
        016 => SpriteDescription {
            top: 1121.0,
            bottom: 1204.0,
            left: 793.0,
            right: 925.0,
        },
        017 => SpriteDescription {
            top: 990.0,
            bottom: 1121.0,
            left: 793.0,
            right: 925.0,
        },
        018 => SpriteDescription {
            top: 891.0,
            bottom: 990.0,
            left: 793.0,
            right: 925.0,
        },
        019 => SpriteDescription {
            top: 0.0,
            bottom: 99.0,
            left: 0.0,
            right: 133.0,
        },
        020 => SpriteDescription {
            top: 99.0,
            bottom: 182.0,
            left: 0.0,
            right: 133.0,
        },
        021 => SpriteDescription {
            top: 594.0,
            bottom: 693.0,
            left: 662.0,
            right: 794.0,
        },
        022 => SpriteDescription {
            top: 495.0,
            bottom: 594.0,
            left: 662.0,
            right: 794.0,
        },
        023 => SpriteDescription {
            top: 396.0,
            bottom: 495.0,
            left: 662.0,
            right: 794.0,
        },
        024 => SpriteDescription {
            top: 297.0,
            bottom: 396.0,
            left: 662.0,
            right: 794.0,
        },
        025 => SpriteDescription {
            top: 198.0,
            bottom: 297.0,
            left: 662.0,
            right: 794.0,
        },
        026 => SpriteDescription {
            top: 380.0,
            bottom: 479.0,
            left: 0.0,
            right: 133.0,
        },
        027 => SpriteDescription {
            top: 1948.0,
            bottom: 2047.0,
            left: 0.0,
            right: 133.0,
        },
        028 => SpriteDescription {
            top: 1946.0,
            bottom: 2045.0,
            left: 661.0,
            right: 793.0,
        },
        029 => SpriteDescription {
            top: 1847.0,
            bottom: 1946.0,
            left: 661.0,
            right: 793.0,
        },
        030 => SpriteDescription {
            top: 1748.0,
            bottom: 1847.0,
            left: 661.0,
            right: 793.0,
        },
        031 => SpriteDescription {
            top: 1649.0,
            bottom: 1748.0,
            left: 661.0,
            right: 793.0,
        },
        032 => SpriteDescription {
            top: 1550.0,
            bottom: 1649.0,
            left: 661.0,
            right: 793.0,
        },
        033 => SpriteDescription {
            top: 1849.0,
            bottom: 1948.0,
            left: 0.0,
            right: 133.0,
        },
        034 => SpriteDescription {
            top: 1552.0,
            bottom: 1651.0,
            left: 0.0,
            right: 133.0,
        },
        035 => SpriteDescription {
            top: 1269.0,
            bottom: 1352.0,
            left: 661.0,
            right: 793.0,
        },
        036 => SpriteDescription {
            top: 1138.0,
            bottom: 1269.0,
            left: 661.0,
            right: 793.0,
        },
        037 => SpriteDescription {
            top: 1055.0,
            bottom: 1138.0,
            left: 661.0,
            right: 793.0,
        },
        038 => SpriteDescription {
            top: 956.0,
            bottom: 1055.0,
            left: 661.0,
            right: 793.0,
        },
        039 => SpriteDescription {
            top: 857.0,
            bottom: 956.0,
            left: 530.0,
            right: 662.0,
        },
        040 => SpriteDescription {
            top: 758.0,
            bottom: 857.0,
            left: 530.0,
            right: 662.0,
        },
        041 => SpriteDescription {
            top: 0.0,
            bottom: 99.0,
            left: 133.0,
            right: 266.0,
        },
        042 => SpriteDescription {
            top: 198.0,
            bottom: 281.0,
            left: 133.0,
            right: 266.0,
        },
        043 => SpriteDescription {
            top: 461.0,
            bottom: 560.0,
            left: 530.0,
            right: 662.0,
        },
        044 => SpriteDescription {
            top: 378.0,
            bottom: 461.0,
            left: 530.0,
            right: 662.0,
        },
        045 => SpriteDescription {
            top: 295.0,
            bottom: 378.0,
            left: 530.0,
            right: 662.0,
        },
        046 => SpriteDescription {
            top: 198.0,
            bottom: 295.0,
            left: 530.0,
            right: 662.0,
        },
        047 => SpriteDescription {
            top: 99.0,
            bottom: 198.0,
            left: 530.0,
            right: 662.0,
        },
        048 => SpriteDescription {
            top: 479.0,
            bottom: 578.0,
            left: 0.0,
            right: 133.0,
        },
        049 => SpriteDescription {
            top: 578.0,
            bottom: 677.0,
            left: 0.0,
            right: 133.0,
        },
        050 => SpriteDescription {
            top: 1834.0,
            bottom: 1933.0,
            left: 529.0,
            right: 661.0,
        },
        051 => SpriteDescription {
            top: 1751.0,
            bottom: 1834.0,
            left: 529.0,
            right: 661.0,
        },
        052 => SpriteDescription {
            top: 1668.0,
            bottom: 1751.0,
            left: 529.0,
            right: 661.0,
        },
        053 => SpriteDescription {
            top: 1585.0,
            bottom: 1668.0,
            left: 529.0,
            right: 661.0,
        },
        054 => SpriteDescription {
            top: 1488.0,
            bottom: 1585.0,
            left: 529.0,
            right: 661.0,
        },
        055 => SpriteDescription {
            top: 1389.0,
            bottom: 1488.0,
            left: 529.0,
            right: 661.0,
        },
        056 => SpriteDescription {
            top: 677.0,
            bottom: 760.0,
            left: 0.0,
            right: 133.0,
        },
        057 => SpriteDescription {
            top: 760.0,
            bottom: 859.0,
            left: 0.0,
            right: 133.0,
        },
        058 => SpriteDescription {
            top: 1108.0,
            bottom: 1191.0,
            left: 529.0,
            right: 661.0,
        },
        059 => SpriteDescription {
            top: 1009.0,
            bottom: 1108.0,
            left: 529.0,
            right: 661.0,
        },
        060 => SpriteDescription {
            top: 926.0,
            bottom: 1009.0,
            left: 398.0,
            right: 530.0,
        },
        061 => SpriteDescription {
            top: 843.0,
            bottom: 926.0,
            left: 398.0,
            right: 530.0,
        },
        062 => SpriteDescription {
            top: 744.0,
            bottom: 843.0,
            left: 398.0,
            right: 530.0,
        },
        063 => SpriteDescription {
            top: 958.0,
            bottom: 1057.0,
            left: 0.0,
            right: 133.0,
        },
        064 => SpriteDescription {
            top: 1057.0,
            bottom: 1156.0,
            left: 0.0,
            right: 133.0,
        },
        065 => SpriteDescription {
            top: 447.0,
            bottom: 546.0,
            left: 398.0,
            right: 530.0,
        },
        066 => SpriteDescription {
            top: 364.0,
            bottom: 447.0,
            left: 398.0,
            right: 530.0,
        },
        067 => SpriteDescription {
            top: 265.0,
            bottom: 364.0,
            left: 398.0,
            right: 530.0,
        },
        068 => SpriteDescription {
            top: 166.0,
            bottom: 265.0,
            left: 398.0,
            right: 530.0,
        },
        069 => SpriteDescription {
            top: 83.0,
            bottom: 166.0,
            left: 398.0,
            right: 530.0,
        },
        070 => SpriteDescription {
            top: 0.0,
            bottom: 83.0,
            left: 398.0,
            right: 530.0,
        },
        071 => SpriteDescription {
            top: 1156.0,
            bottom: 1255.0,
            left: 0.0,
            right: 133.0,
        },
        072 => SpriteDescription {
            top: 1255.0,
            bottom: 1354.0,
            left: 0.0,
            right: 133.0,
        },
        073 => SpriteDescription {
            top: 1745.0,
            bottom: 1828.0,
            left: 397.0,
            right: 529.0,
        },
        074 => SpriteDescription {
            top: 1646.0,
            bottom: 1745.0,
            left: 397.0,
            right: 529.0,
        },
        075 => SpriteDescription {
            top: 1547.0,
            bottom: 1646.0,
            left: 397.0,
            right: 529.0,
        },
        076 => SpriteDescription {
            top: 1464.0,
            bottom: 1547.0,
            left: 397.0,
            right: 529.0,
        },
        077 => SpriteDescription {
            top: 1402.0,
            bottom: 1485.0,
            left: 793.0,
            right: 925.0,
        },
        078 => SpriteDescription {
            top: 760.0,
            bottom: 859.0,
            left: 133.0,
            right: 266.0,
        },
        079 => SpriteDescription {
            top: 182.0,
            bottom: 281.0,
            left: 0.0,
            right: 133.0,
        },
        080 => SpriteDescription {
            top: 792.0,
            bottom: 891.0,
            left: 662.0,
            right: 794.0,
        },
        081 => SpriteDescription {
            top: 0.0,
            bottom: 99.0,
            left: 662.0,
            right: 794.0,
        },
        082 => SpriteDescription {
            top: 99.0,
            bottom: 198.0,
            left: 662.0,
            right: 794.0,
        },
        083 => SpriteDescription {
            top: 723.0,
            bottom: 822.0,
            left: 266.0,
            right: 398.0,
        },
        084 => SpriteDescription {
            top: 1451.0,
            bottom: 1550.0,
            left: 661.0,
            right: 793.0,
        },
        085 => SpriteDescription {
            top: 1352.0,
            bottom: 1451.0,
            left: 661.0,
            right: 793.0,
        },
        086 => SpriteDescription {
            top: 1651.0,
            bottom: 1750.0,
            left: 0.0,
            right: 133.0,
        },
        087 => SpriteDescription {
            top: 281.0,
            bottom: 380.0,
            left: 133.0,
            right: 266.0,
        },
        088 => SpriteDescription {
            top: 659.0,
            bottom: 758.0,
            left: 530.0,
            right: 662.0,
        },
        089 => SpriteDescription {
            top: 560.0,
            bottom: 659.0,
            left: 530.0,
            right: 662.0,
        },
        090 => SpriteDescription {
            top: 0.0,
            bottom: 99.0,
            left: 266.0,
            right: 398.0,
        },
        091 => SpriteDescription {
            top: 1933.0,
            bottom: 2032.0,
            left: 529.0,
            right: 661.0,
        },
        092 => SpriteDescription {
            top: 0.0,
            bottom: 99.0,
            left: 530.0,
            right: 662.0,
        },
        093 => SpriteDescription {
            top: 958.0,
            bottom: 1057.0,
            left: 133.0,
            right: 266.0,
        },
        094 => SpriteDescription {
            top: 859.0,
            bottom: 958.0,
            left: 0.0,
            right: 133.0,
        },
        095 => SpriteDescription {
            top: 1290.0,
            bottom: 1389.0,
            left: 529.0,
            right: 661.0,
        },
        096 => SpriteDescription {
            top: 546.0,
            bottom: 645.0,
            left: 398.0,
            right: 530.0,
        },
        097 => SpriteDescription {
            top: 645.0,
            bottom: 744.0,
            left: 398.0,
            right: 530.0,
        },
        098 => SpriteDescription {
            top: 1238.0,
            bottom: 1369.0,
            left: 265.0,
            right: 397.0,
        },
        099 => SpriteDescription {
            top: 1828.0,
            bottom: 1927.0,
            left: 397.0,
            right: 529.0,
        },
        100 => SpriteDescription {
            top: 1927.0,
            bottom: 2026.0,
            left: 397.0,
            right: 529.0,
        },
        101 => SpriteDescription {
            top: 1453.0,
            bottom: 1552.0,
            left: 0.0,
            right: 133.0,
        },
        102 => SpriteDescription {
            top: 1354.0,
            bottom: 1453.0,
            left: 0.0,
            right: 133.0,
        },
        103 => SpriteDescription {
            top: 822.0,
            bottom: 921.0,
            left: 266.0,
            right: 398.0,
        },
        104 => SpriteDescription {
            top: 624.0,
            bottom: 723.0,
            left: 266.0,
            right: 398.0,
        },
        105 => SpriteDescription {
            top: 525.0,
            bottom: 624.0,
            left: 266.0,
            right: 398.0,
        },
        106 => SpriteDescription {
            top: 1844.0,
            bottom: 1975.0,
            left: 133.0,
            right: 265.0,
        },
        107 => SpriteDescription {
            top: 859.0,
            bottom: 958.0,
            left: 133.0,
            right: 266.0,
        },
        108 => SpriteDescription {
            top: 661.0,
            bottom: 760.0,
            left: 133.0,
            right: 266.0,
        },
        109 => SpriteDescription {
            top: 1057.0,
            bottom: 1188.0,
            left: 133.0,
            right: 265.0,
        },
        110 => SpriteDescription {
            top: 1188.0,
            bottom: 1287.0,
            left: 133.0,
            right: 265.0,
        },
        111 => SpriteDescription {
            top: 1515.0,
            bottom: 1614.0,
            left: 133.0,
            right: 265.0,
        },
        112 => SpriteDescription {
            top: 1287.0,
            bottom: 1386.0,
            left: 133.0,
            right: 265.0,
        },
        113 => SpriteDescription {
            top: 562.0,
            bottom: 661.0,
            left: 133.0,
            right: 266.0,
        },
        114 => SpriteDescription {
            top: 463.0,
            bottom: 562.0,
            left: 133.0,
            right: 266.0,
        },
        115 => SpriteDescription {
            top: 1713.0,
            bottom: 1844.0,
            left: 133.0,
            right: 265.0,
        },
        116 => SpriteDescription {
            top: 99.0,
            bottom: 198.0,
            left: 266.0,
            right: 398.0,
        },
        117 => SpriteDescription {
            top: 1614.0,
            bottom: 1713.0,
            left: 133.0,
            right: 265.0,
        },
        118 => SpriteDescription {
            top: 99.0,
            bottom: 198.0,
            left: 133.0,
            right: 266.0,
        },
        119 => SpriteDescription {
            top: 1765.0,
            bottom: 1864.0,
            left: 265.0,
            right: 397.0,
        },
        120 => SpriteDescription {
            top: 297.0,
            bottom: 426.0,
            left: 266.0,
            right: 398.0,
        },
        121 => SpriteDescription {
            top: 426.0,
            bottom: 525.0,
            left: 266.0,
            right: 398.0,
        },
        122 => SpriteDescription {
            top: 1750.0,
            bottom: 1849.0,
            left: 0.0,
            right: 133.0,
        },
        123 => SpriteDescription {
            top: 198.0,
            bottom: 297.0,
            left: 266.0,
            right: 398.0,
        },
        124 => SpriteDescription {
            top: 1386.0,
            bottom: 1515.0,
            left: 133.0,
            right: 265.0,
        },
        125 => SpriteDescription {
            top: 1266.0,
            bottom: 1365.0,
            left: 397.0,
            right: 529.0,
        },
        126 => SpriteDescription {
            top: 1365.0,
            bottom: 1464.0,
            left: 397.0,
            right: 529.0,
        },
        127 => SpriteDescription {
            top: 1140.0,
            bottom: 1238.0,
            left: 265.0,
            right: 397.0,
        },
        _ => unreachable!(),
    }
}
