#!/bin/sh

set -e
exec < /dev/tty
read -r -p "Would you like to lint your code before committing? [y/N]" response
response=${response,,} # tolower
if [[ $response =~ ^(yes|y|Y) ]]; then
    echo "Linting..."
    cargo +nightly check -q --workspace --all-targets --features empty,optional ||
    echo "Lint Errors Found, Try this command: cargo +nightly fix --workspace --features empty,optional --allow-dirty --allow-staged"
    sleep 1 # fixes possibly newer errors
    cargo +nightly clippy -q -Z unstable-options --workspace --features empty,optional ||
    echo "Lint Errors Found, Try this command: cargo +nightly clippy -Z unstable-options --workspace --features empty,optional --fix --allow-dirty --allow-staged"
    cargo +nightly fmt --all
fi