[package]
name = "amethyst_config"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]
description = "Loading from .yml/.yaml files, with a rust module-like system, into rust structures."

documentation = "https://www.amethyst.rs/doc/amethyst/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT"

[dependencies]
yaml-rust = "0.3.2"
