---
display: 
    brightness: 1.0
    dimensions: [1024, 768]
    fullscreen: false
    max_dimensions: null
    min_dimensions: null
    multisampling: 0
    title: "Amethyst Game"
    visibility: true
    vsync: true
logging: 
    file_path: "new_project.log"
    logging_level: "debug"
    output_level: "warn"
