---
context_config:
    display_config:
        dimensions: null
        fullscreen: false
        max_dimensions: null
        min_dimensions: null
        multisampling: 1
        title: "Amethyst Mesh Demo"
        visibility: true
        vsync: true
        backend: OpenGL

renderer_config:
    pipeline: Forward
    shading: Shaded
    clear_color: [0.0, 0.0, 0.0, 1.0]
