#!/usr/bin/env bash

VERSION="$1"

if [[ "${VERSION}" == "" ]] ; then
  echo -e "Usage: script/set-version X.Y.Z\n\nUpdates all Cargo.toml files with a new version."
  exit 3
fi

function die() {
  echo "$1"
  exit 2
}

which rg > /dev/null || die "Please 'cargo install ripgrep'"

CARGO_TOML_FILES=$(rg '^version =' -t toml -l)

for file in $CARGO_TOML_FILES ; do
  sed -e "s/^version = \".*\"\$/version = \"${VERSION}\"/" -i "" "${file}"
done