---
display: 
  title: Amethyst game
  brightness: 1
  fullscreen: false
  dimensions: 
    - 1024
    - 768
  min_dimensions: ~
  max_dimensions: ~
  vsync: true
  multisampling: 0
  visibility: true
logging: 
  file_path: new_project.log
  output_level: warn
  logging_level: debug